routes/web.php
    Route::get('sub_user_create/{id}', 'UserController@sub_user_create');
    Route::get('display_sub_user/{userid}', 'UserController@display_sub_user');
    Route::get('display_access/{user_id}', 'UserController@display_access');
    Route::resource('roles', 'RoleController');

    Route::resource('setting', 'SettingController');
    Route::resource('blakoutedatesetting', 'BlakoutedateSettingController');
    Route::resource('modules', 'UserModuleController');
//    Route::resource('app-modules', 'AppModulesController');
    Route::resource('amazonsettings', 'AmazonsettingsController');
    Route::resource('inventory', 'InventoryController');
    Route::resource('inbound', 'InboundController');
    Route::resource('replenish', 'ReplenishController');

    Route::resource('report', 'ReportController');
    Route::resource('moduletable', 'ModuletableController');

    Route::resource('memberorder', 'MemberorderController')->middleware('checkType');
    Route::resource('orderreturns', 'MwsOrderReturnsController')->middleware('checkType');
    Route::resource('mws_excess_inventory', 'MwsexcesssinventoryController')->middleware('checkType');
    Route::resource('mws_inventory', 'MwsInventoryController')->middleware('checkType');
    Route::resource('mws_afn_inventory', 'MwsAfnInventoryController')->middleware('checkType');

    Route::resource('purchaseinstances', 'PurchaseInstancesController')->middleware('checkType');
    Route::post('createMore', 'PurchaseInstancesController@createMore');
    Route::resource('purchaseorder', 'PurchaseorderController')->middleware('checkType');
    Route::resource('defaultlogic', 'LogicController')->middleware('checkType');
    Route::get('reorder/{id?}','PurchaseorderController@daily_logic_calculations');

    Route::resource('vendors', 'VendorsController')->middleware('checkType');;
    Route::resource('vendorscontact', 'VendorsContactController')->middleware('checkType');
    Route::resource('vendorsetting', 'VendorsettingController')->middleware('checkType');
    Route::resource('vendor_blackoute_date', 'VendorBlackouteDateController')->middleware('checkType');
    Route::post('changeVendorContact','VendorsController@changeContact');
    Route::get('vendors_bulk_export', 'VendorsController@bulkExport')->name('vendors_bulk_export');
    Route::delete('vendors_bulk_delete', 'VendorsController@bulkDelete')->name('vendors_bulk_delete');
    Route::post('update_vendors_cols', 'VendorsController@updateCols')->name('update_vendors_cols');

    Route::resource('saleshistory', 'SalesHistoryController')->middleware('checkType');
    Route::resource('suppliers', 'SuppliersController')->middleware('checkType');
    Route::delete('suppliers_bulk_delete', 'SuppliersController@bulkDelete')->name('suppliers_bulk_delete');
    Route::get('suppliers_bulk_export', 'SuppliersController@bulkExport')->name('suppliers_bulk_export');
    Route::post('update_suppliers_cols', 'SuppliersController@updateCols')->name('update_suppliers_cols');

    Route::resource('supplierscontact', 'SuppliersContactController')->middleware('checkType');
    Route::resource('suppliersetting', 'SuppliersettingController')->middleware('checkType');
    Route::resource('supplier_blackoute_date', 'SupplierBlackouteDateController')->middleware('checkType');
    Route::post('changeSupplierContact','SuppliersController@changeContact');

    Route::resource('warehouses', 'WarehousesController')->middleware('checkType');
    Route::resource('warehoussetting', 'WarehousesettingController')->middleware('checkType');
    Route::post('changeWarehouseContact','WarehousesController@changeContact');
    Route::delete('warehouses_bulk_delete', 'WarehousesController@bulkDelete')->name('warehouses_bulk_delete');
    Route::get('warehouses_bulk_export', 'WarehousesController@bulkExport')->name('warehouses_bulk_export');
    Route::post('get_warehouses', 'WarehousesController@getData')->name('get_warehouses');
    Route::post('update_warehouses_cols', 'WarehousesController@updateCols')->name('update_warehouses_cols');

    Route::resource('supplyorderlogic','SupplyreorderlogicController')->middleware('checkType');
    Route::resource('fbasetting', 'FbasettingController')->middleware('checkType');

    Route::resource('affiliate_programs', 'AffiliateProgramController');
    Route::post('check_email_exists', 'AffiliateProgramController@check_email_exists');

    /** Products Page */

    Route::get('productsnew', 'MwsProductController@index');
    Route::get('search_product/{search}','MwsProductController@search');
    Route::post('filter_product','MwsProductController@filter');
    Route::delete('products_bulk_delete', function(){ return ['success' => true];})->name('products_bulk_delete');
    Route::post('get_products', function(){ return [];})->name('get_products');
    Route::post('product_add_label', 'MwsProductController@product_add_label')->name('product_add_label');
    Route::post('product_delete_label','MwsProductController@delete_bulk_label')->name('product_delete_label');
    Route::post('product_detail_save', 'MwsProductController@product_detail_save')->name('product_detail_save');
    Route::post('product_cell_change','MwsProductController@product_cell_change')->name('product_cell_change');

    Route::resource('products', 'MwsProductController')->middleware('checkType');
    //Route::get('products-data', 'MwsProductController@products_data');
    Route::get('products_warehouse_assign/{id}','MwsProductController@product_warehouse_assign');
    Route::get('products_sales_rate/{id}','MwsProductController@products_sales_rate');
    Route::post('product_calculation','MwsProductController@product_calculation');

    Route::post('get_data','MwsProductController@get_data');
    Route::get('product_details/{product_id}','MwsProductController@product_details');
    Route::post('crud_process','MwsProductController@crud_process');

    Route::post('import_suppliers', 'SuppliersController@ImportSupplier')->name('import_suppliers');
    Route::get('supplier_import_message', 'SuppliersController@supplier_import_message')->name('supplier_import_message');

    Route::post('import_vendors', 'VendorsController@ImportVendor')->name('import_vendors');
    Route::get('vendor_import_message', 'VendorsController@vendor_import_message')->name('vendor_import_message');

    Route::post('import_shippingagent', 'ShippingAgentController@ImportShippingagent')->name('import_shippingagent');
    Route::get('shippingagent_import_message', 'ShippingAgentController@shippingagent_import_message')->name('shippingagent_import_message');

    Route::post('import_warehouse', 'WarehousesController@ImportWarehouse')->name('import_warehouse');
    Route::get('warehouse_import_message', 'WarehousesController@warehouse_import_message')->name('warehouse_import_message');

    // Route::get('get_products_labels', function(){
    //     return [ 'Label1', 'Label2', 'Label3', 'Label4'];
    // })->name('get_products_labels');

    Route::get('get_products_labels', 'MwsProductController@get_products_labels')->name('get_products_labels');
    //Route::post('product_assign_to_label', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    //Route::get('product_assign_to_label/{label_id}/{product_id}', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    Route::get('get_labels_for_product', 'MwsProductController@get_labels_for_product')->name('get_labels_for_product');

    Route::get('get_sources','MwsProductController@get_sources')->name('get_sources');
    Route::get('apply_bulk_sources','MwsProductController@apply_bulk_sources')->name('apply_bulk_sources');
    Route::post('insert_update_sources','MwsProductController@insert_update_sources')->name('insert_update_sources');
    Route::post('products_bulk_label','MwsProductController@product_assign_to_label')->name('products_bulk_label');
   // Route::post('delete_bulk_label','MwsProductController@delete_bulk_label')->name('delete_bulk_label');

    // Route::post('products_bulk_label', function(Request $request){
    //     return [
    //         'labels' => [
    //             [
    //                 'slug' => 'label1',
    //                 'text' => 'Label 1'
    //             ],
    //             [
    //                 'slug' => 'label2',
    //                 'text' => 'Label 2'
    //             ],
    //             [
    //                 'slug' => 'label3',
    //                 'text' => 'Label 3'
    //             ],
    //             [
    //                 'slug' => 'label4',
    //                 'text' => 'Label 4'
    //             ]
    //         ]
    //     ];
    // })->name('products_bulk_label');

    Route::resource('shippingagent', 'ShippingAgentController')->middleware('checkType');
    Route::get('get_shipping_agent_list','ShippingAgentController@get_shipping_agent_list');
    Route::delete('shipping_agents_bulk_delete', 'ShippingAgentController@bulkDelete')->name('shipping_agents_bulk_delete');
    Route::get('shipping_agents_bulk_export', 'ShippingAgentController@bulkExport')->name('shipping_agents_bulk_export');
    Route::get('get_shipping_agents', 'ShippingAgentController@getData')->name('get_shipping_agents');
    Route::post('update_shipping_agents_cols', 'ShippingAgentController@updateCols')->name('update_shipping_agents_cols');

    Route::get('registertoamazon','AmazonsettingsController@registertoamazon');

    Route::get('logic', function(){ return view('logic.index');});
});
Route::get('/affiliate/{id?}', 'AffiliateProgramController@create_user');
Route::post('forgetpassword', 'SkoteController@forgetpassword');
Route::post('resetpassword', 'SkoteController@resetpassword');
Route::get('/auth/verify/{token}', 'Auth\RegisterController@verifyUser');
//Route::get('/exportdataexcel/{id?}', 'MwsInventoryController@show');

Route::get('dashboard', function(){
    return view('dashboard');
});

resources/views/warehouses/edit-warehouse_old.blade.php
@extends('layouts.master')

@section('title') Edit Warehouse @endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Edit Warehouse</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/index') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('warehouses.index')}}">Warehouse</a></li>
                        <li class="breadcrumb-item active">Edit warehouse</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @if(session()->has('message'))
                {!! session('message') !!}
            @endif
            <div class="card">
                <div class="card-body">

                    <form name="edit-warhouse" id="edit-warhouse" action="{{route('warehouses.update',$warhouse_details['id'])}}" method="POST" onreset="myFunction()">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="insert_type" value="create_form">
                        <div class="form-group row">
                            <label for="example-text-input" class="col-md-2 col-form-label">Type</label>
                            <div class="col-md-4">
                                <select class="custom-select" name="type" id="type">
                                    <option value="1" {{ $warhouse_details->type == 1 ? 'selected' : '' }}>Self</option>
                                    <option value="2" {{ $warhouse_details->type == 2 ? 'selected' : '' }}>Third Party</option>

                                </select>
                            </div>

                            <input type="hidden" name="marketplace_id" id="marketplace_id" value="{{session('MARKETPLACE_ID')}}">

                            <label for="example-text-input" class="col-md-2 col-form-label">Warehouse Name</label>
                            <div class="col-md-4 city">
                                <input class="form-control" type="text" name="warehouse_name" id="warehouse_name" value="{{$warhouse_details['warehouse_name']}}">
                            </div>

                        </div>

                        <div class="form-group row">

                            <label for="example-text-input" class="col-md-2 col-form-label">Address line 1</label>
                            <div class="col-md-4 city">
                                <input class="form-control" type="text" name="address_line_1" id="address" value="{{$warhouse_details['address_line_1']}}">
                            </div>
                            <label for="example-email-input" class="col-md-2 col-form-label">Address line 2</label>
                            <div class="col-md-4">
                                <input class="form-control" type="text" name="address_line_2" value="{{$warhouse_details['address_line_2']}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-tel-input"  class="col-md-2 col-form-label country">Country</label>
                            <div class="col-md-4 country">
                                <select name="country" id="country" class="form-control">
                                    @foreach($country as $key=> $newCountry)
                                        <option value=" {{ $key }}" @if($newCountry== $warhouse_details['country_id']) selected @endif>{{ $key." (". $newCountry." )"  }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <label for="example-text-input" class="col-md-2 col-form-label city">State</label>
                             <div class="col-md-4 country">
                                <select name="state" id="state" class="form-control">
                                    @if(!empty($state_list))
                                    @foreach($state_list as $key=> $state_list)
                                        <option value=" {{ $key }}" @if($key== $warhouse_details['state']) selected @endif>{{ $key." (". $state_list." )"  }}</option>
                                    @endforeach
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-tel-input"  class="col-md-2 col-form-label phone">Cities</label>
                            <div class="col-md-4 phone">
                                <select name="city" id="city" class="form-control">
                                    @if(!empty($city_list))
                                    @foreach($city_list as $key=> $city)
                                        <option value="{{ $key }}" @if($key== $warhouse_details['city']) selected @endif>{{ $key." (". $city." )"  }}</option>
                                    @endforeach
                                    @endif
                                </select>
                            </div>
                            <label for="example-text-input" class="col-md-2 col-form-label state">Zip Code</label>
                            <div class="col-md-4 state">
                                <input class="form-control allow_integer" type="text" name="zipcode" id="zipcode" value="{{$warhouse_details['zipcode']}}" maxlength="6">
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="example-tel-input"  class="col-md-2 col-form-label primary_first_name">Primary Fistname</label>
                            <div class="col-md-4 primary_first_name">
                                <input  class="form-control" type="text" name="primary_first_name" value="{{$warhouse_details['primary_first_name']}}">
                            </div>

                            <label for="example-text-input" class="col-md-2 col-form-label primary_last_name">Primary Lastname</label>
                            <div class="col-md-4 primary_last_name">
                                <input class="form-control" type="text" name="primary_last_name" value="{{$warhouse_details['primary_last_name']}}" >
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-tel-input"  class="col-md-2 col-form-label primary_email" >Primary Email</label>
                            <div class="col-md-4 primary_email">
                                <input  class="form-control" type="email" name="primary_email" value="{{$warhouse_details['primary_email']}}">
                            </div>
                        </div>

                        <div class="button-items mt-3">
                            <input class="btn btn-info" type="submit" value="Submit" id="submit">
                            <a class="btn btn-danger waves-effect waves-light" href="{{ route('warehouses.index') }}" role="button">Cancel</a>
                            <input class="btn btn-warning" type="reset" value="Reset">
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div>
    <!-- end row -->

@endsection

@section('script')
<script>
    $(document).ready(function(){
        $("select").change(function(){
            check();
        }).change();
        check();
    });

    function check() {
      var data= $('#type').val();
         if(data=="1")  {
             $(".primary_first_name").hide();
             $(".primary_last_name").hide();
             $(".primary_email").hide();
             $('.primary_first_name').rules('remove',  {
                 required : true,
                 messages : { required : 'Firstname is required' }
             });
             $('.primary_last_name').rules('remove',  {
                 required : true,
                 messages : { required : 'Lastname is required' }
             });
             $('.primary_email').rules('remove',  {
                 required : true,
                 messages : { required : 'Email is required' }
             });

         }
         else
         {

             $(".primary_first_name").show();
             $(".primary_last_name").show();
             $(".primary_email").show();

                 $('.primary_first_name').rules('add',  {
                     required : true,
                     messages : { required : 'Firstname number is required' }
                 });
                 $('.primary_last_name').rules('add',  {
                     required : true,
                     messages : { required : 'Lastname is required' }
                 });
                 $('.primary_email').rules('add',  {
                     required : true,
                     messages : { required : 'Email is required' }
                 });
            }

    }


    </script>
<script type="text/javascript">

  $('#country').change(function(){
    var country = $(this).val();
    var request_type = 'Get_all_state';
    if(country){
        $.ajax({
           type:"POST",
            url:"{{route('warehouses.store')}}",
            data:{country:country,request_type:request_type},
           success:function(res){
            if(res){
                $("#state").empty();
                $("#state").append('<option>Select</option>');
                $.each(res,function(key,value){
                    $("#state").append('<option value="'+key+'">'+key+'('+value+')'+'</option>');
                });

            }else{
               $("#state").empty();
            }
           }
        });
    }else{
        $("#state").empty();
        $("#city").empty();
    }
   });
    $('#state').on('change',function(){
    var state = $(this).val();
    var request_type = 'Get_all_city';
    if(state){
        $.ajax({
           type:"POST",
            url:"{{ route('warehouses.store') }}",
            data:{state:state,request_type:request_type},
           success:function(res){
            if(res){
                $("#city").empty();
                $("#city").append('<option>Select</option>');
                $.each(res,function(key,value){
                    $("#city").append('<option value="'+key+'">'+key+'('+value+')'+'</option>');
                });

            }else{
               $("#city").empty();
            }
           }
        });
    }else{
        $("#city").empty();
    }

   });
</script>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.master')

@section('title') Warehouse List @endsection

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Warehouse</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/index') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Warehouse</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="form-group row">
        <div class="col-lg-4">
            <a class="btn btn-info waves-effect waves-light mb-3"  href="{{ route('warehouses.create') }}" role="button">Create Warehouse</a>
            <a class="btn btn-info waves-effect waves-light mb-3"  href="{{ route('warehouses.show','import') }}" role="button"><i class="fa fa-download"></i> Download CSV File</a>
        </div>
        <div class="col-lg-8">
        <form action="{{route('warehouses.store')}}" method="post" id="import_csv_warehouse"  enctype="multipart/form-data">
            {{ csrf_field() }}
                <label>Import CSV file : *</label>
                <input type="hidden" name="insert_type" value="upload_csv">
                <input type="file" name="uploadFile" accept=".csv"> <input type="submit" class="btn btn-primary import_csv" value="Import CSV File">
        </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <label class="col-md-2 col-form-label">Select type : </label>
                    <select name="warehouse_type" id="warehouse_type" class="form-control-sm marketplaces_change col-md-2">
                        <option value="1" selected >Self</option>
                        <option value="2">Third Party</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @if(session()->has('message'))
                {!! session('message') !!}
            @endif
            <div class="card">

            </div>
        </div>

    @if(session()->has('message2') || session()->has('message3') || session()->has('message4'))
        <div class="col-lg-12">
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                @if(session()->has('message2'))
                    {!! session('message2') !!}
                @endif
                <br>
                @if(session()->has('message3'))
                    {!! session('message3') !!}
                @endif
                <br>
                @if(session()->has('message4'))
                    {!! session('message4') !!}
                @endif
            </div>
        </div>
        @endif
    </div>
    <!-- end row -->
    <div class="card marketplace_wise_data">
        <div class="card-body">
                <h4 class="card-title mb-4">Warhouse List</h4>
            <div class="table-responsive">
                <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap users-datatable" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead class="thead-light">
                    <tr>
                        <th>No.</th>
                        <th>Warehouse Name</th>
                        <th>Address</th>
                        <th>State</th>
                        <th>Zip Code</th>
                        <th>Country</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
                </div>
            </div>
        </div>

@endsection
@section('script')

<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).on('change','#warehouse_type',function () {
        $.ajax({
            type: "POST",
            url: '{{ route('warehouses.store') }}',
            data: {
                insert_type:"show_type_wise_data",
                id : $(this).val(),
            },
            success: function (response) {
                if(response.error == 0){
                    $('.marketplace_wise_data').html(response.view);
                    $('#datatable').DataTable({});
                }else{
                    alert('Something wrong');
                }
            }
        });

    });
</script>
<script>
    $(document).ready(function () {
                     loadDashboard();

        });
        function loadDashboard(){
           var warehouse_list='warehouse_list';
            var count=1;
            var table = $('#datatable').DataTable({

                "order": [ 0, 'asc' ],
                "bSort": true,
                "paging": true,
                "bInfo": true,
                "bDestroy": true,
                "bFilter": true,
                "searching": true,
                "bPaginate": true,
                "bProcessing": true,
                "language": {
                    "loadingRecords": '&nbsp;',
                    "processing": '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span>'
                },
                'ajax': {
                    "type": "POST",
                    "url": '{{ route('warehouses.store') }}',
                    "data": function (d) {
                        d._token= "{{csrf_token()}}",d.request_type=warehouse_list
                    },
                    "dataType": 'json',
                    "dataSrc": "",
                    "timeout":1000000,
                    "async": true,
                    "cache": true
                },
                success:function($res){
                    console.log(res);
                    return false;
                },
                'columnDefs': [
                    {
                        targets: 0,
                        render: function (data, type, row) {
                            return  count++;
                        }
                    },
                    {
                        targets: 1,
                        render: function (data, type, row) {
                            return  row['warehouse_name'];
                        }
                    },
                    {
                         targets: 2,
                        render: function (data, type, row) {
                            return row['address_line_1'] + "," + row['address_line_2'] + "," + row['city'];
                        }
                    },
                    {
                        targets: 3,
                        render: function (data, type, row) {
                            return row['state'];

                        }
                    },
                    {
                        targets: 4,
                        render: function (data, type, row) {
                            return row['zipcode'];
                        }
                    },
                   
                    {
                        targets: 5,
                        render: function (data, type, row) {
                           return row['country']
                        }
                    },
                    {
                        targets: 6,
                        render: function (data, type, row) {
                            return row['action'];
                        }
                    },
                ]
            });
        }
</script>
<script>
$(document).on('click', '#button', function () {
    //e.preventDefault();
    var $ele = $(this).parent().parent();
    var id = $(this).data('id');
            var url = "{{URL('warehouses')}}";
            var destroyurl = url+"/"+id;


    swal({
             title: "Are you sure?",
            text: "You want to delete this record",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, Delete it!",
            cancelButtonText: "No, cancel please!",
            closeOnConfirm: false,
            closeOnCancel: true
        },
        function(isConfirm) {
            if (isConfirm) {
             
            $.ajax({
                type: "DELETE",
                url:destroyurl, 
                data:{ _token:'{{ csrf_token() }}'},
                dataType: "html",
                success: function (data) {
                    var dataResult = JSON.parse(data);
                if(dataResult.statusCode==200){
                    $ele.fadeOut().remove();
                               swal({
              title: "Done!",
              text: "It was succesfully deleted!",
              type: "success",
              timer: 700
           });
    
                      
                    } 
        }

         });
          }  
    
        else
        {
             swal("Cancelled", "", "error");
        }
            
       
    });

});
</script>    
@endsection