routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
use App\Http\Controllers\SuppliersController;

Route::get('/', function () {
    return redirect('/index');
});

Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/exportdataexcel/{id?}', 'MwsInventoryController@show_new_calculated');
Route::get('/SalesInventoryExport/{id?}','MwsInventoryController@SalesInventoryExport');
Route::get('calculated-excel/{id}', 'HomeController@calculatedExcel');
Route::get('adjusted_inventory_export/{id}', 'HomeController@adjustedInventoryExport');

Route::get('logintoamazon','HomeController@logintoamazon');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/index', 'HomeController@dashboard');
    Route::post('set_marketplace', 'HomeController@set_marketplace');
    Route::resource('users', 'UserController');
    Route::get('sub_user_create/{id}', 'UserController@sub_user_create');
    Route::get('display_sub_user/{userid}', 'UserController@display_sub_user');
    Route::get('display_access/{user_id}', 'UserController@display_access');
    Route::resource('roles', 'RoleController');

    Route::resource('setting', 'SettingController');
    Route::resource('blakoutedatesetting', 'BlakoutedateSettingController');
    Route::resource('modules', 'UserModuleController');
//    Route::resource('app-modules', 'AppModulesController');
    Route::resource('amazonsettings', 'AmazonsettingsController');
    Route::resource('inventory', 'InventoryController');
    Route::resource('inbound', 'InboundController');
    Route::resource('replenish', 'ReplenishController');

    Route::resource('report', 'ReportController');
    Route::resource('moduletable', 'ModuletableController');

    Route::resource('memberorder', 'MemberorderController')->middleware('checkType');
    Route::resource('orderreturns', 'MwsOrderReturnsController')->middleware('checkType');
    Route::resource('mws_excess_inventory', 'MwsexcesssinventoryController')->middleware('checkType');
    Route::resource('mws_inventory', 'MwsInventoryController')->middleware('checkType');
    Route::resource('mws_afn_inventory', 'MwsAfnInventoryController')->middleware('checkType');

    Route::resource('purchaseinstances', 'PurchaseInstancesController')->middleware('checkType');
    Route::post('createMore', 'PurchaseInstancesController@createMore');
    Route::resource('purchaseorder', 'PurchaseorderController')->middleware('checkType');
    Route::resource('defaultlogic', 'LogicController')->middleware('checkType');
    Route::get('reorder/{id?}','PurchaseorderController@daily_logic_calculations');

    Route::resource('vendors', 'VendorsController')->middleware('checkType');;
    Route::resource('vendorscontact', 'VendorsContactController')->middleware('checkType');
    Route::resource('vendorsetting', 'VendorsettingController')->middleware('checkType');
    Route::resource('vendor_blackoute_date', 'VendorBlackouteDateController')->middleware('checkType');
    Route::post('changeVendorContact','VendorsController@changeContact');
    Route::get('vendors_bulk_export', 'VendorsController@bulkExport')->name('vendors_bulk_export');
    Route::delete('vendors_bulk_delete', 'VendorsController@bulkDelete')->name('vendors_bulk_delete');
    Route::post('update_vendors_cols', 'VendorsController@updateCols')->name('update_vendors_cols');

    Route::resource('saleshistory', 'SalesHistoryController')->middleware('checkType');
    Route::resource('suppliers', 'SuppliersController')->middleware('checkType');
    Route::delete('suppliers_bulk_delete', 'SuppliersController@bulkDelete')->name('suppliers_bulk_delete');
    Route::get('suppliers_bulk_export', 'SuppliersController@bulkExport')->name('suppliers_bulk_export');
    Route::post('update_suppliers_cols', 'SuppliersController@updateCols')->name('update_suppliers_cols');

    Route::resource('supplierscontact', 'SuppliersContactController')->middleware('checkType');
    Route::resource('suppliersetting', 'SuppliersettingController')->middleware('checkType');
    Route::resource('supplier_blackoute_date', 'SupplierBlackouteDateController')->middleware('checkType');
    Route::post('changeSupplierContact','SuppliersController@changeContact');

    Route::resource('warehouses', 'WarehousesController')->middleware('checkType');
    Route::resource('warehoussetting', 'WarehousesettingController')->middleware('checkType');
    Route::post('changeWarehouseContact','WarehousesController@changeContact');
    Route::delete('warehouses_bulk_delete', 'WarehousesController@bulkDelete')->name('warehouses_bulk_delete');
    Route::get('warehouses_bulk_export', 'WarehousesController@bulkExport')->name('warehouses_bulk_export');
    Route::post('get_warehouses', 'WarehousesController@getData')->name('get_warehouses');
    Route::post('update_warehouses_cols', 'WarehousesController@updateCols')->name('update_warehouses_cols');

    Route::resource('supplyorderlogic','SupplyreorderlogicController')->middleware('checkType');
    Route::resource('fbasetting', 'FbasettingController')->middleware('checkType');

    Route::resource('affiliate_programs', 'AffiliateProgramController');
    Route::post('check_email_exists', 'AffiliateProgramController@check_email_exists');

    /** Products Page */

    Route::get('productsnew', 'MwsProductController@index');
    Route::get('search_product/{search}','MwsProductController@search');
    Route::post('filter_product','MwsProductController@filter');
    Route::delete('products_bulk_delete', function(){ return ['success' => true];})->name('products_bulk_delete');
    Route::post('get_products', function(){ return [];})->name('get_products');
    Route::post('product_add_label', 'MwsProductController@product_add_label')->name('product_add_label');
    Route::post('product_delete_label','MwsProductController@delete_bulk_label')->name('product_delete_label');
    Route::post('product_detail_save', 'MwsProductController@product_detail_save')->name('product_detail_save');
    Route::post('product_cell_change','MwsProductController@product_cell_change')->name('product_cell_change');

    Route::resource('products', 'MwsProductController')->middleware('checkType');
    //Route::get('products-data', 'MwsProductController@products_data');
    Route::get('products_warehouse_assign/{id}','MwsProductController@product_warehouse_assign');
    Route::get('products_sales_rate/{id}','MwsProductController@products_sales_rate');
    Route::post('product_calculation','MwsProductController@product_calculation');

    Route::post('get_data','MwsProductController@get_data');
    Route::get('product_details/{product_id}','MwsProductController@product_details');
    Route::post('crud_process','MwsProductController@crud_process');

    Route::post('import_suppliers', 'SuppliersController@ImportSupplier')->name('import_suppliers');
    Route::get('supplier_import_message', 'SuppliersController@supplier_import_message')->name('supplier_import_message');

    Route::post('import_vendors', 'VendorsController@ImportVendor')->name('import_vendors');
    Route::get('vendor_import_message', 'VendorsController@vendor_import_message')->name('vendor_import_message');

    Route::post('import_shippingagent', 'ShippingAgentController@ImportShippingagent')->name('import_shippingagent');
    Route::get('shippingagent_import_message', 'ShippingAgentController@shippingagent_import_message')->name('shippingagent_import_message');

    Route::post('import_warehouse', 'WarehousesController@ImportWarehouse')->name('import_warehouse');
    Route::get('warehouse_import_message', 'WarehousesController@warehouse_import_message')->name('warehouse_import_message');

    // Route::get('get_products_labels', function(){
    //     return [ 'Label1', 'Label2', 'Label3', 'Label4'];
    // })->name('get_products_labels');

    Route::get('get_products_labels', 'MwsProductController@get_products_labels')->name('get_products_labels');
    //Route::post('product_assign_to_label', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    //Route::get('product_assign_to_label/{label_id}/{product_id}', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    Route::get('get_labels_for_product', 'MwsProductController@get_labels_for_product')->name('get_labels_for_product');

    Route::get('get_sources','MwsProductController@get_sources')->name('get_sources');
    Route::get('apply_bulk_sources','MwsProductController@apply_bulk_sources')->name('apply_bulk_sources');
    Route::post('insert_update_sources','MwsProductController@insert_update_sources')->name('insert_update_sources');
    Route::post('products_bulk_label','MwsProductController@product_assign_to_label')->name('products_bulk_label');
   // Route::post('delete_bulk_label','MwsProductController@delete_bulk_label')->name('delete_bulk_label');

    // Route::post('products_bulk_label', function(Request $request){
    //     return [
    //         'labels' => [
    //             [
    //                 'slug' => 'label1',
    //                 'text' => 'Label 1'
    //             ],
    //             [
    //                 'slug' => 'label2',
    //                 'text' => 'Label 2'
    //             ],
    //             [
    //                 'slug' => 'label3',
    //                 'text' => 'Label 3'
    //             ],
    //             [
    //                 'slug' => 'label4',
    //                 'text' => 'Label 4'
    //             ]
    //         ]
    //     ];
    // })->name('products_bulk_label');

resources/views/mwsexcessinventory/index.blade.php
@extends('layouts.master')

@section('title') Excess Inventory List @endsection

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Excess Inventory</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/index') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Excess Inventory</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    @if(session()->has('message'))
        {!! session('message') !!}
    @endif

    <!-- end row -->
    <div class="card marketplace_wise_data">
        <div class="card-body">
                <h4 class="card-title mb-4">Excess Inventory List</h4>
            <input type="hidden" value="{{$marketplace}}" name="marketplaces" id="marketplaces">
            <div class="table-responsive">
                <table id="datatables" class="table table-striped table-bordered dt-responsive nowrap users-datatable" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead class="thead-light">
                        <tr>
                            <th>No.</th>
                            <th>FNSKU</th>
                            <th>ASIN</th>
                            <th>Your Price</th>
                            <th>Product Name</th>
                            <th>Updated On</th>
                            <th>Quantity</th>
                            <th>Cost</th>
                        </tr>
                        </thead>
                    <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>        

@endsection
@section('script')
    <script>

        $(document).ready(function () {
            var id = $('#marketplaces').val();
                     loadDashboard(id);
        });
        function loadDashboard(id){
            var count=1;
            var table = $('#datatables').DataTable({
                "order": [ 6, 'desc' ],
                "bSort": true,
                "paging": true,
                "bInfo": true,
                "bDestroy": true,
                "bFilter": true,
                "searching": true,
                "bPaginate": true,
                "bProcessing": true,
                "language": {
                    "loadingRecords": '&nbsp;',
                    "processing": '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span>'
                },
                'ajax': {
                    "type": "POST",
                    "url": "{{ route('mws_excess_inventory.store') }}",
                    "data": function (d) {
                        d._token= "{{csrf_token()}}",d.id=id
                    },
                    "dataType": 'json',
                    "dataSrc": "",
                    "timeout":1000000,
                    "async": true,
                    "cache": true
                },
                'columnDefs': [
                    {
                        targets: 0,
                        render: function (data, type, row) {
                            return  count++;
                        }
                    },
                    {
                        targets: 1,
                        render: function (data, type, row) {
                            return  row['fnsku'];
                        }
                    },
                    {
                        targets: 2,
                        render: function (data, type, row) {
                            return row['asin'];
                        }
                    },
                    {
                        targets: 3,
                        render: function (data, type, row) {
                            return row['your_price'];

                        }
                    },
                    {
                        targets: 4,
                        render: function (data, type, row) {
                            var result = row['product_name'].substring(0, 25)+'...';
                            return pro_name = '<span title="'+row['product_name']+'">'+result+'</span>';
                        }
                    },
                    {
                        targets: 5,
                        render: function (data, type, row) {
                           return row['request_date'];
                        }
                    },
                    {
                        targets: 6,
                        render: function (data, type, row) {
                            return row['total_qty_sellable'];
                        }
                    },
                    {
                        targets: 7,
                        render: function (data, type, row) {
                            return row['buybox_price'];
                        }
                    }
                ]
            });
        }
    </script>
@endsection