routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
use App\Http\Controllers\SuppliersController;

Route::get('/', function () {
    return redirect('/index');
});

Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/exportdataexcel/{id?}', 'MwsInventoryController@show_new_calculated');
Route::get('/SalesInventoryExport/{id?}','MwsInventoryController@SalesInventoryExport');
Route::get('calculated-excel/{id}', 'HomeController@calculatedExcel');
Route::get('adjusted_inventory_export/{id}', 'HomeController@adjustedInventoryExport');

Route::get('logintoamazon','HomeController@logintoamazon');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/index', 'HomeController@dashboard');
    Route::post('set_marketplace', 'HomeController@set_marketplace');
    Route::resource('users', 'UserController');
    Route::get('sub_user_create/{id}', 'UserController@sub_user_create');
    Route::get('display_sub_user/{userid}', 'UserController@display_sub_user');
    Route::get('display_access/{user_id}', 'UserController@display_access');
    Route::resource('roles', 'RoleController');

    Route::resource('setting', 'SettingController');
    Route::resource('blakoutedatesetting', 'BlakoutedateSettingController');
    Route::resource('modules', 'UserModuleController');
//    Route::resource('app-modules', 'AppModulesController');
    Route::resource('amazonsettings', 'AmazonsettingsController');
    Route::resource('inventory', 'InventoryController');
    Route::resource('inbound', 'InboundController');
    Route::resource('replenish', 'ReplenishController');

    Route::resource('report', 'ReportController');
    Route::resource('moduletable', 'ModuletableController');

    Route::resource('memberorder', 'MemberorderController')->middleware('checkType');
    Route::resource('orderreturns', 'MwsOrderReturnsController')->middleware('checkType');
    Route::resource('mws_excess_inventory', 'MwsexcesssinventoryController')->middleware('checkType');
    Route::resource('mws_inventory', 'MwsInventoryController')->middleware('checkType');
    Route::resource('mws_afn_inventory', 'MwsAfnInventoryController')->middleware('checkType');

    Route::resource('purchaseinstances', 'PurchaseInstancesController')->middleware('checkType');
    Route::post('createMore', 'PurchaseInstancesController@createMore');
    Route::resource('purchaseorder', 'PurchaseorderController')->middleware('checkType');
    Route::resource('defaultlogic', 'LogicController')->middleware('checkType');
    Route::get('reorder/{id?}','PurchaseorderController@daily_logic_calculations');

    Route::resource('vendors', 'VendorsController')->middleware('checkType');;
    Route::resource('vendorscontact', 'VendorsContactController')->middleware('checkType');
    Route::resource('vendorsetting', 'VendorsettingController')->middleware('checkType');
    Route::resource('vendor_blackoute_date', 'VendorBlackouteDateController')->middleware('checkType');
    Route::post('changeVendorContact','VendorsController@changeContact');
    Route::get('vendors_bulk_export', 'VendorsController@bulkExport')->name('vendors_bulk_export');
    Route::delete('vendors_bulk_delete', 'VendorsController@bulkDelete')->name('vendors_bulk_delete');
    Route::post('update_vendors_cols', 'VendorsController@updateCols')->name('update_vendors_cols');

    Route::resource('saleshistory', 'SalesHistoryController')->middleware('checkType');
    Route::resource('suppliers', 'SuppliersController')->middleware('checkType');
    Route::delete('suppliers_bulk_delete', 'SuppliersController@bulkDelete')->name('suppliers_bulk_delete');
    Route::get('suppliers_bulk_export', 'SuppliersController@bulkExport')->name('suppliers_bulk_export');
    Route::post('update_suppliers_cols', 'SuppliersController@updateCols')->name('update_suppliers_cols');

    Route::resource('supplierscontact', 'SuppliersContactController')->middleware('checkType');
    Route::resource('suppliersetting', 'SuppliersettingController')->middleware('checkType');
    Route::resource('supplier_blackoute_date', 'SupplierBlackouteDateController')->middleware('checkType');
    Route::post('changeSupplierContact','SuppliersController@changeContact');

    Route::resource('warehouses', 'WarehousesController')->middleware('checkType');
    Route::resource('warehoussetting', 'WarehousesettingController')->middleware('checkType');
    Route::post('changeWarehouseContact','WarehousesController@changeContact');
    Route::delete('warehouses_bulk_delete', 'WarehousesController@bulkDelete')->name('warehouses_bulk_delete');
    Route::get('warehouses_bulk_export', 'WarehousesController@bulkExport')->name('warehouses_bulk_export');
    Route::post('get_warehouses', 'WarehousesController@getData')->name('get_warehouses');
    Route::post('update_warehouses_cols', 'WarehousesController@updateCols')->name('update_warehouses_cols');

    Route::resource('supplyorderlogic','SupplyreorderlogicController')->middleware('checkType');
    Route::resource('fbasetting', 'FbasettingController')->middleware('checkType');

    Route::resource('affiliate_programs', 'AffiliateProgramController');
    Route::post('check_email_exists', 'AffiliateProgramController@check_email_exists');

    /** Products Page */

    Route::get('productsnew', 'MwsProductController@index');
    Route::get('search_product/{search}','MwsProductController@search');
    Route::post('filter_product','MwsProductController@filter');
    Route::delete('products_bulk_delete', function(){ return ['success' => true];})->name('products_bulk_delete');
    Route::post('get_products', function(){ return [];})->name('get_products');
    Route::post('product_add_label', 'MwsProductController@product_add_label')->name('product_add_label');
    Route::post('product_delete_label','MwsProductController@delete_bulk_label')->name('product_delete_label');
    Route::post('product_detail_save', 'MwsProductController@product_detail_save')->name('product_detail_save');
    Route::post('product_cell_change','MwsProductController@product_cell_change')->name('product_cell_change');

    Route::resource('products', 'MwsProductController')->middleware('checkType');
    //Route::get('products-data', 'MwsProductController@products_data');
    Route::get('products_warehouse_assign/{id}','MwsProductController@product_warehouse_assign');
    Route::get('products_sales_rate/{id}','MwsProductController@products_sales_rate');
    Route::post('product_calculation','MwsProductController@product_calculation');

    Route::post('get_data','MwsProductController@get_data');
    Route::get('product_details/{product_id}','MwsProductController@product_details');
    Route::post('crud_process','MwsProductController@crud_process');

    Route::post('import_suppliers', 'SuppliersController@ImportSupplier')->name('import_suppliers');
    Route::get('supplier_import_message', 'SuppliersController@supplier_import_message')->name('supplier_import_message');

    Route::post('import_vendors', 'VendorsController@ImportVendor')->name('import_vendors');
    Route::get('vendor_import_message', 'VendorsController@vendor_import_message')->name('vendor_import_message');

    Route::post('import_shippingagent', 'ShippingAgentController@ImportShippingagent')->name('import_shippingagent');
    Route::get('shippingagent_import_message', 'ShippingAgentController@shippingagent_import_message')->name('shippingagent_import_message');

    Route::post('import_warehouse', 'WarehousesController@ImportWarehouse')->name('import_warehouse');
    Route::get('warehouse_import_message', 'WarehousesController@warehouse_import_message')->name('warehouse_import_message');

    // Route::get('get_products_labels', function(){
    //     return [ 'Label1', 'Label2', 'Label3', 'Label4'];
    // })->name('get_products_labels');

    Route::get('get_products_labels', 'MwsProductController@get_products_labels')->name('get_products_labels');
    //Route::post('product_assign_to_label', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    //Route::get('product_assign_to_label/{label_id}/{product_id}', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    Route::get('get_labels_for_product', 'MwsProductController@get_labels_for_product')->name('get_labels_for_product');

    Route::get('get_sources','MwsProductController@get_sources')->name('get_sources');
    Route::get('apply_bulk_sources','MwsProductController@apply_bulk_sources')->name('apply_bulk_sources');
    Route::post('insert_update_sources','MwsProductController@insert_update_sources')->name('insert_update_sources');
    Route::post('products_bulk_label','MwsProductController@product_assign_to_label')->name('products_bulk_label');
   // Route::post('delete_bulk_label','MwsProductController@delete_bulk_label')->name('delete_bulk_label');

    // Route::post('products_bulk_label', function(Request $request){
    //     return [
    //         'labels' => [
    //             [
    //                 'slug' => 'label1',
    //                 'text' => 'Label 1'
    //             ],
    //             [
    //                 'slug' => 'label2',
    //                 'text' => 'Label 2'
    //             ],
    //             [
    //                 'slug' => 'label3',
    //                 'text' => 'Label 3'
    //             ],
    //             [
    //                 'slug' => 'label4',
    //                 'text' => 'Label 4'
    //             ]
    //         ]
    //     ];
    // })->name('products_bulk_label');

app/Models/Purchase_instances.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\SoftDeletes;



class Purchase_instances  extends Model
{
    use SoftDeletes;
    protected $table = 'purchase_instances';

    protected $fillable = [
        'user_marketplace_id',
        'track_id',
        'status'
       
    ];
    /**
     * Get the purchase instance details for the purchase instance.
     *
     * @param  no-params
     *
     */
    public function purchase_instances_details(){
        return $this->hasOne('App\Models\Purchase_instance_details','purchesinstances_id');
    }
    /**
     * Get the purchase order details for the purchase instance.
     *
     * @param  no-params
     *
     */
     public function purchase_order_details(){
        return $this->hasMany('App\Models\Purchase_order_details','purchesinstances_id');
    }
    /**
     * Get the product for the purchase instance.
     *
     * @param  no-params
     *
     */
     public function product(){
        return $this->hasOne('App\Models\Mws_product','id');
    }
    /**
     * Get the supplier for the purchase instance.
     *
     * @param  no-params
     *
     */
     public function suppliers(){
        return $this->hasOne('App\Models\Supplier','id');
    }
    /**
     * Get the user marketplace that owns the purchase instance..
     *
     * @param  no-params
     *
     */
    public function usermarketplace(){
        return $this->belongsTo('App\Models\Usermarketplace', 'user_marketplace_id');
    }
    

}

resources/views/purchaseinstances/edit.blade.php
@extends('layouts.master')

@section('title') Update Puraches Instances @endsection

@section('content')
    <style>
        .design{
            cursor: no-drop;
            color: #74788d !important;
            background-color: #eff2f7 !important;
        }
    </style>
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Update Puraches Instances</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/index') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('purchaseinstances.index') }}">Puraches Instances</a></li>
                        <li class="breadcrumb-item active">Update Puraches Instances</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @if(session()->has('message'))
                {!! session('message') !!}
            @endif
            <div class="card">
                <div class="card-body">
                    <form name="edit-puraches_instances" id="edit-puraches_instances" action="{{ route('purchaseinstances.update',$id) }}" method="POST" onreset="myFunction()">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="input_type" value="Create_form">
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label">Select Products</label>
                            <div class="col-md-4">
                                <select class="product_listing custom-select js-delivery @error('product_id') is-invalid @enderror" name="product_id" id="product_id">
                                    <option value="">Select Products</option>
                                    @if(!empty($products))
                                        @foreach($products as $list)
                                            @if($list['mws_product']['prod_name'] !=  '' && $list['mws_product']['prod_name'] != '-')
                                                <option value="{{ $list['mws_product']['id'] }}" title="{{$list['mws_product']['prod_name']}}">{{substr(strip_tags( $list['mws_product']['prod_name']),0,25)."..."}}</option>
                                            @endif
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <input type="hidden" name="vendors_select_id" id="vendors_select_id" value="">
                            <input type="hidden" name="suppliers_select_id" id="suppliers_select_id" value="">
                            <input type="hidden" name="warehouse_select_id" id="warehouse_select_id" value="">

                            <label class="col-md-2 col-form-label">Vendor/Supplier</label>
                            <div class="col-md-4">
                                <input type="text" class="form-control design" value=" - " id="vendors_suppliers_name" disabled>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 col-form-label">Warehouse</label>
                            <div class="col-md-4">
                                <input type="text" class="form-control design" value=" - " id="warehouse_name" disabled>
                            </div>
                            <label class="col-md-2 col-form-label">Projected Units</label>
                            <div class="col-md-4">
                                <input class="form-control @error('projected_units') is-invalid @enderror" type="text" value="{{ isset($purchase_details->projected_units) && $purchase_details->projected_units != '' ? $purchase_details->projected_units : '' }}" name="projected_units" id="projected_units">
                                @if ($errors->has('projected_units'))
                                    <span class="invalid-feedback" role="alert"><strong>{{ $errors->first('projected_units') }}</strong></span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-md-2 col-form-label">Items/Cartoons</label>
                            <div class="col-md-4">
                                <input class="form-control @error('items_per_cartoons') is-invalid @enderror" type="text" value="{{ isset($purchase_details->items_per_cartoons) && $purchase_details->items_per_cartoons != '' ? $purchase_details->items_per_cartoons : '' }}" name="items_per_cartoons" id="items_per_cartoons">
                                @if ($errors->has('items_per_cartoons'))
                                    <span class="invalid-feedback" role="alert"><strong>{{ $errors->first('items_per_cartoons') }}</strong></span>
                                @endif
                            </div>
                            <label class="col-md-2 col-form-label">Containers</label>
                            <div class="col-md-4">
                                <input class="form-control @error('containers') is-invalid @enderror" type="text" value="{{ isset($purchase_details->containers) && $purchase_details->containers != '' ? $purchase_details->containers : '' }}" name="containers" id="containers">
                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert"><strong>{{ $errors->first('containers') }}</strong></span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label">CBM</label>
                            <div class="col-md-4">
                                <input class="form-control @error('cbm') is-invalid @enderror " type="text" value="{{ isset($purchase_details->cbm) && $purchase_details->cbm != '' ? $purchase_details->cbm : '' }}" name="cbm" id="cbm">
                                @if ($errors->has('cbm'))
                                    <span class="invalid-feedback" role="alert"><strong class="errors">{{ $errors->first('cbm') }}</strong></span>
                                @endif
                            </div>
                            <label class="col-md-2 col-form-label">Sub Total</label>
                            <div class="col-md-4">
                                <input  class="form-control @error('subtotal') is-invalid @enderror" type="text" value="{{ isset($purchase_details->subtotal) && $purchase_details->subtotal != '' ? $purchase_details->subtotal: ''  }}" name="subtotal" id="subtotal" maxlength="15">
                                @if ($errors->has('subtotal'))
                                    <span class="invalid-feedback" role="alert"><strong class="errors">{{ $errors->first('subtotal') }}</strong></span>
                                @endif
                            </div>
                        </div>

                        <div class="button-items mt-3">
                            <input class="btn btn-info" type="submit" value="Submit" id="submit">
                            <a class="btn btn-danger waves-effect waves-light" href="{{ route('purchaseinstances.index') }}" role="button">Cancel</a>
                            <input class="btn btn-warning" type="reset" value="Reset">
                        </div>

                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div>
    <!-- end row -->

@endsection

@section('script')
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script>

        $("#projected_units").keypress(function (e)
        {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        $("#items_per_cartoons").keypress(function (e)
        {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        $("#containers").keypress(function (e)
        {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        $("#cbm").keypress(function (e)
        {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
        $("#subtotal").keypress(function (e)
        {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });

    </script>
    <script>
        $(document).ready(function(){
            var id = $('.product_listing').val();
            get_product_datas(id);
        });
        $(document).on('change','.product_listing',function() {
            var id = $(this).val();
            get_product_datas(id);
        });
        function get_product_datas(id){
            var dataroletype = 'vendors_suppliers_warehouse';
            $.ajax({
                type: "POST",
                url: '{{ route('purchaseinstances.store') }}',
                data: {
                    product_id : id,
                    input_type : dataroletype,
                },
                success: function (response) {
                    $('#vendors_select_id').val(response.vendors_id);
                    $('#suppliers_select_id').val(response.suppliers_id);
                    $('#warehouse_select_id').val(response.warehouseid);
                    $('#vendors_suppliers_name').val(response.vendors_suppliers_name);
                    $('#warehouse_name').val(response.warehousename);
                }
            });
        }
    </script>


    <script>
   $(function () {

       $('#datatables').DataTable({
           "pageLength": 10,
           'autoWidth': false,
           "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
       });
   });
</script>

@endsection

resources/views/purchaseinstances/purchase_instanceview.blade.php
@extends('layouts.master')

@section('title') Purchase Instance View @endsection

@section('content')


<style>
    .design{
         font-style:bold;
         font-size:14px;         

    }
    </style>

<style>
table, th, td {
  border: 2px solid ;
  border-collapse: collapse;
}
</style>    
    <div class="row">
        <div class="col-12">

            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Purchase Instance View</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/index') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('purchaseinstances.index')}}">Purchase Instance</a></li>
                        <li class="breadcrumb-item active"> Purchase Instance View</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
   <div class="row">
            <div class="col-12">
                @if(session()->has('message'))
                    {!! session('message') !!}
                @endif
                <div class="card">
                    @php($vendors_suppliers_name = ' - ')
                    @if(isset($view->purchase_instances_details->supplier) && $view->purchase_instances_details->supplier != 0)
                        @php($vendors_suppliers_name = get_suppliers_name($view->purchase_instances_details->supplier))
                    @endif
                    @if(isset($view->purchase_instances_details->vendor) && $view->purchase_instances_details->vendor != 0)
                        @php($vendors_suppliers_name = get_vendors_name($view->purchase_instances_details->vendor))
                    @endif
                    @php($warehouse_name = ' - ')
                    @if(isset($view->purchase_instances_details->warehouse) && $view->purchase_instances_details->warehouse != 0)
                        @php($warehouse_name = get_product_warehouse_name($view->purchase_instances_details->warehouse))
                    @endif

                    <div class="card-body">
                        
                            <!-- <div class="form-group row"> -->

                                
                                <div  style="margin-bottom: 10px;">
                                    <span style="font-size: 15px;color:black;">Date:</span>&nbsp;&nbsp;
                                        {{date('Y-m-d',strtotime($view['created_at']))}} &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
                                   <span style="font-size: 15px;color:black;"> Track Id:</span>&nbsp;&nbsp;{{isset($view->track_id) && $view->track_id != '' ? $view->track_id : ''}} &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;

                                    <span style="font-size: 15px;color:black;">Status:</span>&nbsp;&nbsp;{{isset($view->status) && $view->status != '' && $view->status == 2 ? 'completed' : 'pending'}}

                            </div> 
              
                        <div class="box">
                        
                            <table class="table table-striped table-bordered dt-responsive nowrap datatable" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead class="thead-light">
                                <tr>
                                    <th>No.</th>
                                    <th>Product</th>
                                    <th>SKU</th>
                                    <th>Vendor/Supplier </th>
                                    <th>Warehouse</th>
                                    <th>Projected Units</th>
                                    <th>Items/Cartons</th>
                                    <th>CBM</th>
                                    <th>Containers</th>
                                    <th>Subtotal</th>
                                   
                                </tr>
                                </thead>
                                <tbody>
                                <?php $no = 1; ?>
                                    @if(!empty($purchase_details))
                                    @foreach($purchase_details as $users)
                                        @php($vendors_suppliers_name = ' - ')
                                        @php($get_warehouse_name = ' - ')
                                        @php($product_name = ' - ')

                                        @if($users['supplier'] != 0)
                                            @php($vendors_suppliers_name = get_suppliers_name($users['supplier']))
                                        @endif
                                        @if($users['vendor'] != 0)
                                            @php($vendors_suppliers_name = get_vendors_name($users['vendor']))
                                        @endif
                                        @if($users['warehouse'])
                                            @php($get_warehouse_name = get_warehouse_name($users['warehouse']))
                                        @endif
                                        @if($users['product_id'])
                                            @php($product_name = get_product_details($users['product_id']))
                                        @endif

                                        @php($product_sku = ' - ')
                                        @if(isset($order['product_id']) && $order['product_id'] != 0)
                                            @php($product_sku = get_product_sku($order['product_id']))
                                        @endif

                                        <tr id="row{{$users['id']}}">
                                            <td id="rows_no{{$users['id']}}">{{$no++}}</td>
                                            <td id="product_name_no{{$users['id']}}" title="{{$product_name}}">{{substr(strip_tags($product_name),0,25)."..."}}</td>
                                             <td>{{isset($product_sku) && $product_sku != '' ? $product_sku : ''}}</td>
                                            <td id="product_suppliers_name{{$users['id']}}">{{$vendors_suppliers_name}}</td>
                                            <td id="warehouse{{$users['id']}}">{{$get_warehouse_name}}</td>
                                            <td id="projected_units{{$users['id']}}">{{$users['projected_units']}}</td>
                                            <td id="items_per_cartoons{{$users['id']}}">{{$users['items_per_cartoons']}}</td>
                                            <td id="cbm{{$users['id']}}">{{$users['cbm']}}</td>
                                            <td id="containers{{$users['id']}}">{{$users['containers']}}</td>
                                            <td id="subtotal{{$users['id']}}">{{$users['subtotal']}}</td>
                                            
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                            <div class="button-items mt-3" align="center">
                            <a class="btn btn-info" href="{{ route('purchaseinstances.index') }}" role="button" style="width:116px;">Back</a>
                        </div>
                    </div>
                
            <!-- </div> -->
   </div>
@endsection
@section('script')

<script>
   $(function () {

       $('.datatable').DataTable({
           "pageLength": 10,
           'autoWidth': false,
           "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
       });
   });
</script>

@endsection