routes/web.php
    Route::resource('inbound', 'InboundController');
    Route::resource('replenish', 'ReplenishController');

    Route::resource('report', 'ReportController');
    Route::resource('moduletable', 'ModuletableController');

    Route::resource('memberorder', 'MemberorderController')->middleware('checkType');
    Route::resource('orderreturns', 'MwsOrderReturnsController')->middleware('checkType');
    Route::resource('mws_excess_inventory', 'MwsexcesssinventoryController')->middleware('checkType');
    Route::resource('mws_inventory', 'MwsInventoryController')->middleware('checkType');
    Route::resource('mws_afn_inventory', 'MwsAfnInventoryController')->middleware('checkType');

    Route::resource('purchaseinstances', 'PurchaseInstancesController')->middleware('checkType');
    Route::post('createMore', 'PurchaseInstancesController@createMore');
    Route::resource('purchaseorder', 'PurchaseorderController')->middleware('checkType');
    Route::resource('defaultlogic', 'LogicController')->middleware('checkType');
    Route::get('reorder/{id?}','PurchaseorderController@daily_logic_calculations');

    Route::resource('vendors', 'VendorsController')->middleware('checkType');;
    Route::resource('vendorscontact', 'VendorsContactController')->middleware('checkType');
    Route::resource('vendorsetting', 'VendorsettingController')->middleware('checkType');
    Route::resource('vendor_blackoute_date', 'VendorBlackouteDateController')->middleware('checkType');
    Route::post('changeVendorContact','VendorsController@changeContact');
    Route::get('vendors_bulk_export', 'VendorsController@bulkExport')->name('vendors_bulk_export');
    Route::delete('vendors_bulk_delete', 'VendorsController@bulkDelete')->name('vendors_bulk_delete');
    Route::post('update_vendors_cols', 'VendorsController@updateCols')->name('update_vendors_cols');

    Route::resource('saleshistory', 'SalesHistoryController')->middleware('checkType');
    Route::resource('suppliers', 'SuppliersController')->middleware('checkType');
    Route::delete('suppliers_bulk_delete', 'SuppliersController@bulkDelete')->name('suppliers_bulk_delete');
    Route::get('suppliers_bulk_export', 'SuppliersController@bulkExport')->name('suppliers_bulk_export');
    Route::post('update_suppliers_cols', 'SuppliersController@updateCols')->name('update_suppliers_cols');

    Route::resource('supplierscontact', 'SuppliersContactController')->middleware('checkType');
    Route::resource('suppliersetting', 'SuppliersettingController')->middleware('checkType');
    Route::resource('supplier_blackoute_date', 'SupplierBlackouteDateController')->middleware('checkType');
    Route::post('changeSupplierContact','SuppliersController@changeContact');

    Route::resource('warehouses', 'WarehousesController')->middleware('checkType');
    Route::resource('warehoussetting', 'WarehousesettingController')->middleware('checkType');
    Route::post('changeWarehouseContact','WarehousesController@changeContact');
    Route::delete('warehouses_bulk_delete', 'WarehousesController@bulkDelete')->name('warehouses_bulk_delete');
    Route::get('warehouses_bulk_export', 'WarehousesController@bulkExport')->name('warehouses_bulk_export');
    Route::post('get_warehouses', 'WarehousesController@getData')->name('get_warehouses');
    Route::post('update_warehouses_cols', 'WarehousesController@updateCols')->name('update_warehouses_cols');

    Route::resource('supplyorderlogic','SupplyreorderlogicController')->middleware('checkType');
    Route::resource('fbasetting', 'FbasettingController')->middleware('checkType');

    Route::resource('affiliate_programs', 'AffiliateProgramController');
    Route::post('check_email_exists', 'AffiliateProgramController@check_email_exists');

    /** Products Page */

    Route::get('productsnew', 'MwsProductController@index');
    Route::get('search_product/{search}','MwsProductController@search');
    Route::post('filter_product','MwsProductController@filter');
    Route::delete('products_bulk_delete', function(){ return ['success' => true];})->name('products_bulk_delete');
    Route::post('get_products', function(){ return [];})->name('get_products');
    Route::post('product_add_label', 'MwsProductController@product_add_label')->name('product_add_label');
    Route::post('product_delete_label','MwsProductController@delete_bulk_label')->name('product_delete_label');
    Route::post('product_detail_save', 'MwsProductController@product_detail_save')->name('product_detail_save');
    Route::post('product_cell_change','MwsProductController@product_cell_change')->name('product_cell_change');

    Route::resource('products', 'MwsProductController')->middleware('checkType');
    //Route::get('products-data', 'MwsProductController@products_data');
    Route::get('products_warehouse_assign/{id}','MwsProductController@product_warehouse_assign');
    Route::get('products_sales_rate/{id}','MwsProductController@products_sales_rate');
    Route::post('product_calculation','MwsProductController@product_calculation');

    Route::post('get_data','MwsProductController@get_data');
    Route::get('product_details/{product_id}','MwsProductController@product_details');
    Route::post('crud_process','MwsProductController@crud_process');

    Route::post('import_suppliers', 'SuppliersController@ImportSupplier')->name('import_suppliers');
    Route::get('supplier_import_message', 'SuppliersController@supplier_import_message')->name('supplier_import_message');

    Route::post('import_vendors', 'VendorsController@ImportVendor')->name('import_vendors');
    Route::get('vendor_import_message', 'VendorsController@vendor_import_message')->name('vendor_import_message');

    Route::post('import_shippingagent', 'ShippingAgentController@ImportShippingagent')->name('import_shippingagent');
    Route::get('shippingagent_import_message', 'ShippingAgentController@shippingagent_import_message')->name('shippingagent_import_message');

    Route::post('import_warehouse', 'WarehousesController@ImportWarehouse')->name('import_warehouse');
    Route::get('warehouse_import_message', 'WarehousesController@warehouse_import_message')->name('warehouse_import_message');

    // Route::get('get_products_labels', function(){
    //     return [ 'Label1', 'Label2', 'Label3', 'Label4'];
    // })->name('get_products_labels');

    Route::get('get_products_labels', 'MwsProductController@get_products_labels')->name('get_products_labels');
    //Route::post('product_assign_to_label', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    //Route::get('product_assign_to_label/{label_id}/{product_id}', 'MwsProductController@product_assign_to_label')->name('product_assign_to_label');
    Route::get('get_labels_for_product', 'MwsProductController@get_labels_for_product')->name('get_labels_for_product');

    Route::get('get_sources','MwsProductController@get_sources')->name('get_sources');
    Route::get('apply_bulk_sources','MwsProductController@apply_bulk_sources')->name('apply_bulk_sources');
    Route::post('insert_update_sources','MwsProductController@insert_update_sources')->name('insert_update_sources');
    Route::post('products_bulk_label','MwsProductController@product_assign_to_label')->name('products_bulk_label');
   // Route::post('delete_bulk_label','MwsProductController@delete_bulk_label')->name('delete_bulk_label');

    // Route::post('products_bulk_label', function(Request $request){
    //     return [
    //         'labels' => [
    //             [
    //                 'slug' => 'label1',
    //                 'text' => 'Label 1'
    //             ],
    //             [
    //                 'slug' => 'label2',
    //                 'text' => 'Label 2'
    //             ],
    //             [
    //                 'slug' => 'label3',
    //                 'text' => 'Label 3'
    //             ],
    //             [
    //                 'slug' => 'label4',
    //                 'text' => 'Label 4'
    //             ]
    //         ]
    //     ];
    // })->name('products_bulk_label');

    Route::resource('shippingagent', 'ShippingAgentController')->middleware('checkType');
    Route::get('get_shipping_agent_list','ShippingAgentController@get_shipping_agent_list');
    Route::delete('shipping_agents_bulk_delete', 'ShippingAgentController@bulkDelete')->name('shipping_agents_bulk_delete');
    Route::get('shipping_agents_bulk_export', 'ShippingAgentController@bulkExport')->name('shipping_agents_bulk_export');
    Route::get('get_shipping_agents', 'ShippingAgentController@getData')->name('get_shipping_agents');
    Route::post('update_shipping_agents_cols', 'ShippingAgentController@updateCols')->name('update_shipping_agents_cols');

    Route::get('registertoamazon','AmazonsettingsController@registertoamazon');

    Route::get('logic', function(){ return view('logic.index');});
});
Route::get('/affiliate/{id?}', 'AffiliateProgramController@create_user');
Route::post('forgetpassword', 'SkoteController@forgetpassword');
Route::post('resetpassword', 'SkoteController@resetpassword');
Route::get('/auth/verify/{token}', 'Auth\RegisterController@verifyUser');
//Route::get('/exportdataexcel/{id?}', 'MwsInventoryController@show');

Route::get('dashboard', function(){
    return view('dashboard');
});

Route::post('suppliers_filter', function(){ return []; })->name('suppliers.filter');
Route::post('vendors_filter', function(){  return []; })->name('vendors.filter');
Route::post('warehoused_filter', function(){ return [];})->name('warehouses.filter');
Route::post('shipping_agents_filter', function(){ return [];})->name('shipping_agents.filter');

Route::post('products_filter', function(){ return [];})->name('products.filter');

Route::post('get_suppliers', 'SuppliersController@getData')->name('get_suppliers');
Route::post('get_vendors', 'VendorsController@getData')->name('get_vendors');

Route::get('countries', function(){
    return get_country_list();

app/Models/ShippingAgent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ShippingAgent extends Model
{
    use SoftDeletes;
    protected $table = 'shipping_agents';

    protected $fillable = [
        'user_marketplace_id',
        'country_id',
        'company_name',
        'first_name',
        'last_name',
        'email',
        'phone'
    ];

    /**
     * Get the user marketplace that owns the shipping agent.
     *
     * @param  no-params
     *
     */
    public function usermarketplace(){
        return $this->belongsTo('App\Models\Usermarketplace', 'user_marketplace_id');
    }
}

resources/views/shipping_agent/create.blade.php
@extends('layouts.master-new')

@section('title') Create Shipping Agent @endsection

@section('content')

<div class="suppliers-top-main-box">
    <div class="row">
        <div class="col-md-4">
            <div class="suppliers-first-column">
                <h2>Shipping Agent</h2>
            </div>
        </div>
    </div>
</div>
<div class="suppliers-main-box suppliers-main-box-scroll">
    <div class="row">
        <div class="suppliers-logistics-agent-2">
            <form class="main-address-from d-block" name="create-shipping-agent" id="create-shipping-agent" action="{{ route('shippingagent.store') }}" method="POST" >
                @csrf
                <input type="hidden" name="insert_type" value="create_form">
                <input type="hidden" name="marketplace_id" id="marketplace_id" value="{{session('MARKETPLACE_ID')}}">
                <!-- <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Supplier Name <span>*</span></li>
                        <li>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Enter Supplier Name">
                            </div>
                        </li>
                    </ul>
                </div> -->
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Shipping Agent</li>
                        <li>
                            <div class="form-group">
                                <select class="form-control" id="exampleFormControlSelect1" id="country" name="country">
                                    <option>Select Shipping Agent</option>
                                    @foreach($country as $countries)
                                    <option value="{{ $countries['id'] }}">{{ $countries['country_name'] }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Company</li>
                        <li>
                            <div class="form-group">
                                <input type="text" class="form-control" name="company_name" id="company_name" placeholder="Enter Company Name">
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>First Name</li>
                        <li>
                            <div class="form-group">
                                <input type="text" class="form-control"  name="first_name" id="first_name" placeholder="Enter First Name">
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Last Name</li>
                        <li>
                            <div class="form-group">
                                <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name">
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Email</li>
                        <li>
                            <div class="form-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="suppliers-address-box">
                    <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                        <li>Phone Number</li>
                        <li>
                            <div class="form-group">
                                <input type="text" class="form-control" name="phone" id="phone" placeholder="Phone Number">
                            </div>
                        </li>
                    </ul>
                </div>
                <ul class="d-flex flex-row justify-content-between">
                    <li>
                        <button type="submit" class="btn address-cancel-btn">Cancel</button>
                    </li>
                    <li>
                        <button type="button" class="btn btn-primary">Save</button>
                        <button type="submit" class="btn address-save-btn">Save And Next</button>
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/shipping_agent/edit-shipping_agent.blade.php
@extends('layouts.master-new')

@section('title') Edit Shipping Agent @endsection

@section('content')
    <div class="suppliers-top-main-box">
        <div class="row">
            <div class="col-md-4">
                <div class="suppliers-first-column">
                    <h2>Shipping Agent</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="suppliers-main-box suppliers-main-box-scroll">
        <div class="row">
            <div class="suppliers-logistics-agent-2">
                <form class="main-address-from" name="edit-shipping-agent" id="edit-shipping-agent" action="{{ route('shippingagent.update',$shipping_agent['id']) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <input type="hidden" name="insert_type" value="edit_form">
                    <input type="hidden" name="marketplace_id" id="marketplace_id" value="{{session('MARKETPLACE_ID')}}">
                    <!-- <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Supplier Name <span>*</span></li>
                            <li>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Enter Supplier Name">
                                </div>
                            </li>
                        </ul>
                    </div> -->
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Shipping Agent</li>
                            <li>
                                <div class="form-group">
                                    <select class="form-control" id="exampleFormControlSelect1" name="country">
                                        <option>Select Shipping Agent</option>
                                        @foreach($country as $countries)
                                            <option value="{{ $countries['id'] }}" @if($countries['id']== $shipping_agent['country_id']) selected @endif>{{ $countries['country_name'] }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Company</li>
                            <li>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="company_name" id="company_name" placeholder="Enter Company Name" value="{{ $shipping_agent['company_name'] }}">
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>First Name</li>
                            <li>
                                <div class="form-group">
                                    <input type="text" class="form-control"  name="first_name" id="last_name" placeholder="Enter First Name" value="{{ $shipping_agent['first_name'] }}">
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Last Name</li>
                            <li>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name" value="{{ $shipping_agent['last_name'] }}">
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Email</li>
                            <li>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email" value="{{ $shipping_agent['email'] }}">
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul class="d-flex flex-row align-items-center justify-content-between pb-3">
                            <li>Phone Number</li>
                            <li>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="phone" id="phone" placeholder="Phone Number" value="{{ $shipping_agent['phone'] }}">
                                </div>
                            </li>
                        </ul>
                    </div>
                    <ul class="d-flex flex-row justify-content-between">
                        <li>
                            <button type="submit" class="btn address-cancel-btn">Cancel</button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-primary">Save</button>
                            <button type="submit" class="btn address-save-btn">Save And Next</button>
                        </li>
                    </ul>
                </form>
                <div class="address-save-form">
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>Shipping Agent</li>
                            @php($get_country_name = get_country_name($shipping_agent['country_id']))
                            <li class="address-save-right">
                                <p>{{$get_country_name}}<span class="suppliers-address-box-icon"
                                                                   onclick="editeAdress()"><svg
                                                xmlns="http://www.w3.org/2000/svg"
                                                width="13.208" height="13.208"
                                                viewBox="0 0 13.208 13.208">
                                                                            <g id="Icon_feather-edit"
                                                                               data-name="Icon feather-edit"
                                                                               transform="translate(1)">
                                                                                <path id="Path_314" data-name="Path 314"
                                                                                      d="M8.46,6H4.213A1.213,1.213,0,0,0,3,7.213v8.494a1.213,1.213,0,0,0,1.213,1.213h8.494a1.213,1.213,0,0,0,1.213-1.213V11.46"
                                                                                      transform="translate(-3 -4.713)"
                                                                                      fill="none" stroke="#227cff"
                                                                                      stroke-linecap="round"
                                                                                      stroke-linejoin="round"
                                                                                      stroke-width="2" />
                                                                                <path id="Path_315" data-name="Path 315"
                                                                                      d="M18.37,3.195a1.287,1.287,0,0,1,1.82,1.82l-5.764,5.764L12,11.386l.607-2.427Z"
                                                                                      transform="translate(-8.36 -2.818)"
                                                                                      fill="#227cff" />
                                                                            </g>
                                                                        </svg>
                                                                    </span></p>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>Company</li>
                            <li class="address-save-right">
                                <p>{{$shipping_agent['company_name']}}</p>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>First Name</li>
                            <li class="address-save-right">
                                <p>{{$shipping_agent['first_name']}}</p>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>Last Name</li>
                            <li class="address-save-right">
                                <p>{{$shipping_agent['last_name']}}</p>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>Email</li>
                            <li class="address-save-right">
                                <p>{{$shipping_agent['email']}}</p>
                            </li>
                        </ul>
                    </div>
                    <div class="suppliers-address-box">
                        <ul
                                class="d-flex flex-row align-items-start justify-content-between pb-3">
                            <li>Phone Number</li>
                            <li class="address-save-right">
                                <p>{{$shipping_agent['phone']}}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/shipping_agent/import_messages.blade.php
@extends('layouts.master-final')

@section('title') Shipping agent Import Messages @endsection

@section('customcss')
    <style>
        table td{
            vertical-align: middle !important;
        }
    </style>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Shipping agent</h4>
           	<a href="{{ url('shippingagent') }}" class="btn btn-primary waves-effect waves-light">
                    <!-- <i class="bx bx-plus-circle align-middle mr-2"></i> -->Back To shipping agent
                </a>
        </div>
    </div>
</div>
@if($total_count != '')
	<div class="alert alert-danger">
		Total {{$total_count != '' ? $total_count : 0 }} rows uploaded {{$success_count != '' ? $success_count : 0}} successfully uploaded and {{$error_count != '' ? $error_count : 0}} failed to upload
	</div>
@endif	
@if(!empty($error_msg))
	<table id="list" class="table dataTable table-striped dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
        <thead class="" style="background-color: #49505710;">
	        <tr>
	            <td>S/N</td>
	            <td>Shipping agent</td>
	            <td>Error</td>
	        </tr>
        </thead>
       	<tbody>
       		<?php
       		for($i=0;$i<count($error_msg);$i++){
       			//dump($error_msg[$i]);
       		?>
       			<tr>
       				<td>{{$i+1}}</td>
       				<td>{{($error_msg[$i]['companyname'] ?? '')}}</td>
       				<td>{{$error_msg[$i]['message']}}</td>
       			</tr>
       		</tbody>
       		<?php
       		}
       		?>
       	</tbody>
       
    </table>
<!-- @else
	@if($success_msg)
	<div class="alert alert-success">
		{{($success_msg ?? '')}}
	</div>
	@else
	<p>No Data Found</p>
	@endif -->
@endif
@endsection
<?php
\Session::forget('error_msg_array');
        \Session::forget('success_message');
?>